[package]
name = "snake_game"
version = "0.1.0"
authors = ["David Avendaño <d.avendano.c@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
